name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: build
    - uses: actions/checkout@v2
    - run: |
        export LBL=$(date +%s)
        echo "::set-env name=LBL::$LBL"
    - run: docker build . --file dynamodb_local/Dockerfile --tag krystan/dynamodb:$LBL

    - name: Log in to Docker Hub
    - uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}    
  
    - name: push image
      run: docker push krystan/dynamodb:$LBL
